### ISSUE TITLE
"user is drunk" video on youtube is set to private - cant see it 

### ISSUE THREAD

**Issue by d2a-raudenaerde** [elementary/hig#43]
## What Happened
Clicking the video on https://docs.elementary.io/hig/design-philosophy does not play the video. (https://www.youtube.com/watch?v=r2CbbBLVaPk)

## Expected Behavior
I would expect to see the video 

## Steps to Reproduce
Open https://www.youtube.com/watch?v=r2CbbBLVaPk

## Platform Information
Ubuntu 20.04

![image](https://user-images.githubusercontent.com/5213150/129019885-e979dd77-b6de-4ba0-9772-2b5c6ec79c9b.png)

**Comment by lenemter** [comment]
It's not private now, just unlisted
