### ISSUE TITLE
Add HIG page for Toast

### ISSUE THREAD

**Issue by zeebok** [elementary/hig#55]
### Problem

The page exists for Toasts but it is currently entirely empty!

### Proposal

Write a guide about the feature, when to use it, how to style it, etc.

**Comment by danirabbit** [comment]
There is a Toasts section here: https://docs.elementary.io/hig/widgets/providing-feedback

Is the empty page being linked to from another section?

**Comment by zeebok** [comment]
The Interactive Widgets dropdown in the navigation leads here: https://docs.elementary.io/hig/widgets/ui-toolkit-elements/toast

**Comment by danirabbit** [comment]
Ah okay. Removed the dead page :+1:
